### ISSUE TITLE
Add concept of warning

### ISSUE THREAD

**Issue by mattdell** [vitkon/form-container#33]
Currently form-container has validators and those validators are able to invalidate the form and issue an error to the input when failed. A feature I would like to request is the concept of a warning. Warnings would have the same validation interface as an error but will populate a `hasWarning` boolean to complement the `hasError` boolean for errors. A warning would not invalidate a form; it would only exist at the field level.

Inspiration for this concept comes from our friends at redux-form:
https://redux-form.com/7.3.0/docs/api/field.md/#-code-warn-value-allvalues-props-gt-warning-code-optional-

Also see their validation example:
https://redux-form.com/7.3.0/examples/syncvalidation/

Example
<img width="646" alt="screen shot 2018-03-15 at 14 35 22" src="https://user-images.githubusercontent.com/2536442/37469852-255a2874-285e-11e8-98cb-759e309ff933.png">

**Comment by mattdell** [comment]
I'm going to take the two thumbs up as approval to add this feature.

**Comment by zsid** [comment]
I am looking forward to it. Happy to help with implementation

**Comment by vitkon** [comment]
@zsid PRs are welcome

**Comment by mattdell** [comment]
PR raised #35 

Can we add @zsid as a contributor?

**Comment by vitkon** [comment]
only if he gives us a star ;)

For this kind of changes it's better to discuss the new API first before diving into implementation

**Comment by vitkon** [comment]
1. is breaking change needed? other options considered
2. is there a way to gradually deprecate old functionality?

**Comment by mattdell** [comment]
1. I suppose we could use the syntax of `connectForm(validators, { warnings })` for the interim, but it's not as clean as `connectForm({ errors, warnings })`.
1. There isn't any functionality going away, it's just updating the interface to take a configuration object which will allow us to update the API in the future with a smaller chance of breaking something.

**Comment by vitkon** [comment]
naming of the keys implies that these are errors and warnings, but they are validators with a different type. do you think we can still use validators but pass some params into validationRule factory?

**Comment by mattdell** [comment]
Yeah, I debated the naming a bit. The naming convention of `{ errorValidators, warningValidators }` could also work.

How would you envision passing params into `validators` as its type is simply `ValidationRule[]`?

**Comment by vitkon** [comment]
I meant something like this:

```
export const ValidationRuleFactory: any = (
    validationFn: (value: any, allProps?: any) => boolean,
    errorMessage: string
): ValidationRule => (prop, message = errorMessage, type = 'error') => [
    (model, allProps) => validationFn(model[prop], allProps),
    { [prop]: message },
    { type }
];
```

it complicates the validation rule api, which is not ideal, but worth considering

**Comment by mattdell** [comment]
I'm not totally against it. I wonder from an interface view what seems easier to use for a user...

```
connectForm({
  errorValidators: [],
  warningValidators: [],
})(Form);
```

or

```
connectForm([
  isRequired('dob', 'Date of birth is required'),
  isDobOver18('dob', 'You must be at least 18 years old', 'warning')
], config);
```

Also better again to take an object instead of `(prop, message = errorMessage, type = 'error')` because to send a warning you'd have to override the error message so better to do...

```
export const ValidationRuleFactory: any = (
    validationFn: (value: any, allProps?: any) => boolean,
    errorMessage: string
): ValidationRule => ({ prop, message = errorMessage, type = 'error' }) => [
    (model, allProps) => validationFn(model[prop], allProps),
    { [prop]: message },
    { type }
];
```

And then you can say

```
  isDobOver18('dob', 'warning')
```

I'm just about to hop on a plane so it would be a good use of my time to implement one of these approaches. What do you think is best @vitkon ? I do think the `validators` first param needs to go as part of v1 but I suppose we could get it done this way first so not to break anything currently.

**Comment by mattdell** [comment]
Actually, the more I think about it that's the best solution for now.

Going to work to implement

```
export const ValidationRuleFactory: any = (
    validationFn: (value: any, allProps?: any) => boolean,
    errorMessage: string
): ValidationRule => (prop, message = errorMessage, type = 'error') => [
    (model, allProps) => validationFn(model[prop], allProps),
    { [prop]: message },
    { type }
];
```

But maybe with a `ValidationType` instead of a string?

```
enum ValidationType {
  error,
  warning
}
```

**Comment by vitkon** [comment]
```
const enum ValidationType {
   Error = 'error'.
   Warning = 'warning'
}
```

**Comment by vitkon** [comment]
#39 merged
