### ISSUE TITLE
Add method to set validation errors/warnings on fields outside of validation rules

### ISSUE THREAD

**Issue by huwmartin** [vitkon/form-container#62]
Currently all `validationErrors` and `validationWarnings` are constructed based on the validation rules in `validate`. A feature I would like to propose for consideration is an alternative method to set validation errors/warnings outside of validation rules.

The primary use-case I have come across for this is the need to set validation errors/warnings in response to back-end errors i.e. where we post a payload to a service and it fails back-end validation and returns an error code so we need to set form errors accordingly.

[Redux Form has the concept of](https://redux-form.com/7.4.2/docs/api/submissionerror.md/) `SubmissionError` which can be thrown in a request `catch` with an object containing field errors and is caught by Redux Form to set said field errors.
#
You can find a practical example of the usage in Redux Form [here](https://redux-form.com/7.4.2/examples/submitvalidation/).

**Comment by vitkon** [comment]
Should the server-side validation and related props come as a prop from above?
Not sure if it's a form's concern.

What do you think?

**Comment by huwmartin** [comment]
I think it makes some sense to have it handled by the form as you want the errors to be dismissed on change of values for the given fields so that the user can attempt to submit again, in that case having it contained within the form makes things easier.

It seems like a somewhat common use-case to me - in our case we are saving bank details to a back-end service and the service is applying additional verification to confirm that:

1) the input is a valid account number + sort code combination
2) that the input is not a duplicate of an existing saved account

I think I've seen similar patterns for account creation though, i.e. username is taken; email already exists; new password is one of the previous *x* passwords.

I'm going to raise a PR for consideration to present how I think this could be handled, it is closely following the approach of Redux form by providing a `handleSubmit` function and a throwable `SubmissionError`. Would appreciate you input on this or whether you think the use-case is better served by some middleware (although again in this case it would be more difficult to catch and set the submit errors)?
