### ISSUE TITLE
TypeScript definitions have not been updated for release of v0.2.6

### ISSUE THREAD

**Issue by huwmartin** [vitkon/form-container#65]
## Expected Behaviour

Should be able to import `SubmissionError` and use `handleSubmit` and `clearSubmitError` in `formMethods`.

## Actual Behaviour

For the latest release v0.2.6 the index.d.ts file in the dist has not been updated to include the updated definitions with these exports. When I run `npm run build` locally these are included. Can we attempt to build the release again and update it?

**Comment by vitkon** [comment]
Indeed, it didn't make it into the build for some reason. Publishing v2.7 to fix.
